services:
  - type: web
    name: paynow-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: CORS_ORIGIN
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
        # This should be a JSON string of your Firebase service account
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_SHORTCODE
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
    healthCheckPath: /api/health
